project                  = "minecraft-servers"
region                   = "eu-west-1"
default_az               = "a"
zone_name                = "benedekkovacs.co.uk"
default_server_file_path = "https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar"
default_instance_type    = "r7g.medium"
